---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: client,client1
  vars:
    motd_redhat: "welcome to redhat linux\n"
    motd_ubuntu: "welcome to ubuntu linux \n"
  
  tasks:
    - name: install openjdk
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == "RedHat"
    - name: install openjdk in ubuntu
      apt:
        name: openjdk-11-jdk-headless
        state: present 
      when: ansible_distribution == "Ubuntu"
    - name: download maven package 
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
    - name: untar the maven package
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
    - name: symbolic link for apache maven
      file: 
        src: /opt/apache-maven-3.8.6
        dest: /opt/maven
        state: link
      
