---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: client,client1
  vars:
    motd_redhat: "welcome to redhat linux\n"
    motd_ubuntu: "welcome to ubuntu linux \n"
  
  tasks:
    - name: install epel release 
    #epel enterprise linux it is being specially created for redhat based system
      dnf: 
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        update_cache: yes
        state: present #present or absent
      when: ansible_distribution == "RedHat"
    - name: install nginx
      package: 
      #this module autmatically identify the os and run the installation command accoring to your os
        name: nginx 
        state: latest
    - name: restart nginx server
      service:
      #systemctl restart httpd service
        name: nginx 
        state: restarted
      notify: check http service 
    - name: add port in firewalld
    #by default when you install redhat it get installed with firewalld a inbuilt firewall in your redhat based system
      firewalld:
        service: http 
        permanent: true 
        state: enabled 
      when: ansible_distribution == "RedHat"
      notify: Reload Firewalld 
  handlers:
    - name: check http service
      uri: 
        url: http://{{ ansible_default_ipv4.address }}
        status_code: 200
    - name: Reload Firewalld
      service:
        name: firewalld
        state: reloaded    