---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: winhost
  tasks:
    - name: choco install package 
      win_chocolatey: 
        name: procexp
        state: present